trunk/src/objects/Field_Show_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Value_to_Show__c</fullName>
        <description>Field with defined name must have this value in order to show field attached field</description>
        <label>Value to Show</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Field Show Rule</label>
    <nameField>
        <label>Field Show Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Show Rule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

trunk/src/classes/ShowRule.cls
// Wrapper class for Field_Show_Rule__c for conditional field display 

public class ShowRule {

  		public List<String> valuesToShow {get; set;}
  		public String firstValueToShow {get; set;}
  		public String groupName {get; set;}
  		
  		public ShowRule(Field_Show_Rule__c showRule)
  		{
  			valuesToShow = showRule.Value_to_Show__c.split(',');
  			if (valuesToShow.size() > 0)
      			firstValueToShow = valuesToShow.remove(0);
  			groupName = showRule.name;
  		}
	
	
}