trunk/src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Finished_Blurb__c</fullName>
        <description>HTML to display to user when they are finished with the form.</description>
        <label>Finished Blurb</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Object_Label__c</fullName>
        <description>The label of the object which fields will be filled by this form.</description>
        <inlineHelpText>The label of the object which fields will be filled by this form.</inlineHelpText>
        <label>Object Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>The API name of the object which fields will be filled by this form.</description>
        <inlineHelpText>The API name of the object which fields will be filled by this form.</inlineHelpText>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Save_Button_Text__c</fullName>
        <defaultValue>&quot;Save&quot;</defaultValue>
        <description>The text that will appear on the form&apos;s save button.</description>
        <inlineHelpText>The text that will appear on the form&apos;s save button.</inlineHelpText>
        <label>Save Button Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text_Color__c</fullName>
        <label>Text Color</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title of the form.</description>
        <inlineHelpText>The title that will appear on the form. This can be left blank.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Inquiry Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/classes/FormDemoController.cls
public with sharing class FormDemoController extends PageControllerBase {
	 
	  public ApexPages.StandardController standardCon { get; set; }
	  public String fieldName 						{ get; set; }
	  public Form__c form 							{ get; set; }   
	  public String formname 						{ get; set; }
	  public SObject activeSObject  				{ get; set; }  
	  public FormController myComponentController 	{ get; set; }      

    public FormDemoController() {
    	
        formname = ApexPages.CurrentPage().getParameters().get('name');

        try {
		    form = [select Id, Name, Object_Name__c, Finished_Blurb__c, Object_Label__c, Title__c, Save_Button_Text__c, Text_Color__c from Form__c where name = :formName];          
	 	  	Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
	        SObjectType sot = gd.get(form.Object_Name__c);
	        try {
	            myObject = sot.newSObject();
	        }
	        catch(System.NullPointerException ex) {
	            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The system can not create a form for : '+ form.Object_Name__c));
	        }
        
        }
        catch (QueryException qe)
        {
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There is no form with this name.'));
			return;      	
        }
        
        System.debug('form is:' + formName);
               
    }
	   	  
	  public void save()
	  {
	  	ecSave();
	  }
	  

}